import Head from 'next/head';

const HeadComponent: React.FC = () => {
  return (
    <Head>
      <title>Ride</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadComponent;