import Head from 'next/head'
import Image from 'next/image'
import HeaderComponent from '../components/HeaderComponent'
import FooterComponent from '../components/FooterComponent'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ride</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <FooterComponent />
    </div>
  )
}
