import Head from 'next/head'
import Image from 'next/image'
import HeaderComponent from '../components/HeaderComponent'
import FooterComponent from '../components/FooterComponent'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ride</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <main>
        <section></section>
        <section>
          <div>
            <p>▷ Depuis 2008, RIDE, agence de location de voitures de luxe propose ses services partout en France (Paris, Monaco, Nice, Cannes, Saint-Tropez, Courchevel, Saint-Moritz...).</p>
            <p>Notre expérience est à votre service pour répondre à toutes vos demandes</p>
            <hr />
          </div>
        </section>
      </main>

      <FooterComponent />
    </div>
  )
}
