
const HeadComponent: React.FC = () => {
  return (
    <>
      <title>Ride</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default HeadComponent;